---
galaxy_info:
  author: Armada Team
  description: Deploy Kyverno policy engine using Helm in HA mode
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Kubernetes
      versions:
        - all

  galaxy_tags:
    - kubernetes
    - kyverno
    - security
    - policy
    - helm

dependencies: []
